version: '3.8'
services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: hello_cargo
      POSTGRES_USER: hello_cargo
      POSTGRES_PASSWORD: NotSoStrongPassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: